### ISSUE TITLE
Not clear how to express "list of 2-tuples"

### ISSUE THREAD

**Issue by ambivalentno** [genomoncology/related#14]
So, I've looked at SequenceField and it's not quite clear for me should I do that in correct way.
At the moment, I can say each of two-tuples is an object with both attributes of float type.
But I don't feel it's a correct approach.

**Comment by ambivalentno** [comment]
@imaurer bump!

**Comment by imaurer** [comment]
Since YAML and JSON don't roundtrip to and from tuples, I don't think this is in scope of related. I would recommend putting in getter/setter properties or some other mechanism to transform to and from tuples.

Sorry for the delayed response.
