### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by HyuanTan** [genomoncology/related#30]
Hi, thanks for share! 
When in import related, I got the import error like:
```
from attr import attrs
ImportError: cannot import name attrs
```
I use the newest version of attrs v18.2.0. Did I install the wrong version of attrs?
Thanks for help!

**Comment by imaurer** [comment]
From the unit tests, version 18.2 of attrs is working fine:
https://travis-ci.org/genomoncology/related/jobs/450215119

Looks like you might have some confusion with your virtualenv. What does this say?

```
$ pip freeze
attrs==18.2.0
future==0.17.1
python-dateutil==2.7.5
PyYAML==3.13
related==0.7.1
six==1.11.0
```
