### ISSUE TITLE
Support newer Attrs library

### ISSUE THREAD

**Issue by Avsecz** [genomoncology/related#6]
Currently, related can't be used alongside the current `pytest-cov` and `pytest-pep8` libraries. These require a more recent version of `attrs` (>= 17.2.0), whereas related is fixed at 17.1.0 -
 https://github.com/genomoncology/related/blob/master/setup.py#L30

```python
pluggy.PluginValidationError: Plugin 'pytest_cov' could not be loaded: (attrs 17.1.0 
...
, Requirement.parse('attrs>=17.2.0'), {'pytest'})!
```

Would it be possible to support and test also more recent versions of attrs in related?

**Comment by imaurer** [comment]
Glad to have your feedback. Let me see what I can do. Shouldn't be terribly hard and I use the same pytest libraries that you use, just must be on an earlier version of them.

**Comment by imaurer** [comment]
I pushed up 0.6. Let me know if upgrading fixes you issue. I assume you might need to upgrade both at the same time... just a guess.

```
pip install -U attrs related
```

**Comment by Avsecz** [comment]
Great. All my tests pass except one. I'm raising an error if there are extra fields in the yaml file (and are not specified in the class). 

I have seen that you now only take out the keys which you are able to parse:
https://github.com/genomoncology/related/blob/master/src/related/functions.py#L99-L118

```python
def to_model(cls, value):
    """
    Coerce a value into a model object based on a class-type (cls).
    :param cls: class type to coerce into
    :param value: value to be coerced
    :return: original value or coerced value (value')
    """

    if isinstance(value, cls) or value is None:
        pass  # skip if right type or value is None

    elif issubclass(cls, Enum):
        value = cls(value)

    elif is_model(cls) and isinstance(value, dict):
        value = convert_key_to_attr_names(cls, value)
        value = cls(**value)

    else:
        value = cls(value)

    return value


def convert_key_to_attr_names(cls, original):
    """ convert key names to their corresponding attribute names """
    attrs = fields(cls)
    updated = {}

    for a in attrs:
        key_name = a.metadata.get('key') or a.name
        if key_name in original:
            updated[a.name] = original.get(key_name)

    return updated
```

Would it make sense to have an optional flag in `to_model`, say `no_extra_keys` that would raise an error in case the user specified some extra fields?

**Comment by Avsecz** [comment]
Anyway, I found a way how to work around this - I check the arguments myself before calling to_model. Feel free to close this issue. Thanks!

**Comment by Avsecz** [comment]
Ok. My fix doesn't work in general for nested Child classes. I'll close this issue and open another one
