### ISSUE TITLE
Optional warning when parsing yaml fields not specified in the model class

### ISSUE THREAD

**Issue by Avsecz** [genomoncology/related#8]
A use-case would be that the package-writer specifies the following yaml:

```python
@related.immutable
class Person(object):
    first_name = related.StringField()
    last_name = related.StringField(required=False, default="Doe")
```

and the user inputs the following yaml:

```yaml
first_name: Grace
last_nam: Hopper
```

In that case, the user made a typo specfying the `last_name` parameter. However, this will go unnoticed since related ignores the fields it is not able to parse https://github.com/genomoncology/related/blob/master/src/related/functions.py#L99-L118

```python
>>> import related
>>> @related.immutable
... class Person(object):
...     first_name = related.StringField()
...     last_name = related.StringField(required=False, default="Doe")
... 
>>> yaml_str = """
... first_name: Grace
... last_nam: Hopper
... """
>>> from related import from_yaml, to_model
>>> to_model(Person, from_yaml(yaml_str))
Person(first_name='Grace', last_name='Doe')
```

Would it make sense to have an optional flag in `to_model`, say `no_extra_keys` that would raise a warning/Exception with an informative error message in case the user specified some extra fields?

**Comment by imaurer** [comment]
Thinking about this some and I am torn.

Does it make sense to generate a validation schema from the related models and then use something like Cerebus to validate?

http://docs.python-cerberus.org/en/stable/index.html

Or accept the fact that related already does validation and this is just another type.

I am wondering if we need a "Meta" class like sqlalchemy or django do to store things like this


`
>>> import related
>>> @related.immutable
... class Person(object):
...     first_name = related.StringField()
...     last_name = related.StringField(required=False, default="Doe")
...         class Meta(related.meta):
...             strict = True
`

**Comment by Avsecz** [comment]
I find embedding the logic into the class like you proposed really nice. All the configuration is in one place, so it's much easier to grasp than. 

Alternatively, one could put the arguments into the decorator

```python
import related

@related.immutable(strict=True)
class Person(object):
    first_name = related.StringField()
    last_name = related.StringField()
```

**Comment by imaurer** [comment]
I like your idea much better.

**Comment by imaurer** [comment]
How about this...

`
    >>> import related
    >>> @related.immutable(strict=True)
    ... class Person(object):
    ...     first_name = related.StringField()
    ...     last_name = related.StringField()
    ... 
    >>> d = dict(first_name="Grace", last_name="Hopper", extra="Failure!")
    >>> related.to_model(Person, d)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/ianmaurer/oss/related/src/related/functions.py", line 99, in to_model
        value = convert_key_to_attr_names(cls, value)
      File "/Users/ianmaurer/oss/related/src/related/functions.py", line 123, in convert_key_to_attr_names
        raise ValueError("Extra keys (strict mode): {}".format(extra))
    ValueError: Extra keys (strict mode): {'extra'}    
`

**Comment by imaurer** [comment]
This is the commit. If all passes on travis, I will push up 0.6.1
https://github.com/genomoncology/related/commit/b82bfe59ea8a3a11e458f94d1b060e98905ed53f

**Comment by imaurer** [comment]
Pushed up.

**Comment by Avsecz** [comment]
wow. Nice!:))

**Comment by Avsecz** [comment]
btw, you can use `pytest.raises` in your unit-tests with py.test:

```python
with pytest.raises(ValueError) as excinfo:
   # expect ValueError
   related.to_model(Person, d)
```
