### ISSUE TITLE
MappingField and null

### ISSUE THREAD

**Issue by ifoukarakis** [genomoncology/related#9]
Hi,

Thanks for the great work! I recently started using it and it's going really good so far. However I run into a problem.  See the following case:

```python
import related

@related.immutable
class Root(object):
    children = related.MappingField(Child, 'name', required=False)

@related.immutable
class Child(object):
    name = related.StringField()
    values = related.SequenceField(str, required=False)

result = related.from_yaml('''
children:
''', Root)
```
`Root.children` is not required. Using the input YAML, it will be `null`. When the actual instance is going to be created, it raises an exception. I would expect that result.children would be null instead. What do you think?

**Comment by imaurer** [comment]
Thanks for the feedback. I definitely don't think this should raise an exception. Let me make a unit test and figure out a good default behavior that roundtrips correctly to and from YAML.

**Comment by imaurer** [comment]
@ifoukarakis check out the commits I just made:

First one round trips into this:
```
children: {}
```

Second one, converts to:
```
children: null
```

**Comment by ifoukarakis** [comment]
I think that `children: {}` is better matched for MappingField. I see the following benefits:
- User has defined that he's expecting a MappingField (and not null).
- It's a bit more defensive programming vs null.
- Output is `{}` rather than an empty string, which is a strong indication to the user that this is a mapping. However this might be a bit of a problem. If you try to just load and dump a file, you won't get exactly the same output.

**Comment by imaurer** [comment]
_If you try to just load and dump a file, you won't get exactly the same output._

I think that's why I am leaning towards leaving it as None so it roundtrips. People could always put the empty dictionary there if that's what they wish. If I force it to dictionary, you cannot ever get a None value to retain.
